version: "3.9"
services:
  arangodb:
    container_name: remedi_conta
    image: arangodb/arangodb:3.12.4
    restart: unless-stopped
    environment:
      - ARANGO_ROOT_PASSWORD=perplexity
    ports:
      - "8529:8529"
    command: ["arangod", "--experimental-vector-index", "true"]
    volumes:
      - arango_data:/var/lib/arangodb3

volumes:
  arango_data:

